name: Autograding

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          # Install any dependencies your autograder requires
          pip install -r requirements.txt

      - name: Run autograder
        run: |
          # Execute your autograding script
          python test_html.py

      - name: Debug the results file
        run: |
          cat results.json
          # Ensure the results file has the correct format and is non-empty

      - name: Upload results
        id: autograder_results
        run: |
          # Ensure the file isn't empty before passing it to the environment variable
          if [[ -s results.json ]]; then
            echo "result=$(cat results.json)" >> $GITHUB_ENV
          else
            echo "Error: results.json is empty!" >> $GITHUB_ENV
            exit 1
          fi

      - name: Debug environment variable
        run: echo "AUTOGRADER_RESULTS is: ${{ env.result }}"

      - name: Report results to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: autograder
        env:
          AUTOGRADER_RESULTS: ${{ env.result }}